### ISSUE TITLE
Error when installing version 1.0.1 

### ISSUE THREAD

**Issue by AlaaL** [iyzico/iyzipay-magento2#20]
Hello I am installing iyzipay 1.0.1 on magento 2.4.2 and when executing `php bin/magento setup:di:compile`
I got this output 

```
Fatal error: Uncaught Error: Class 'Iyzico\Iyzipay\Block\Adminhtml\Totals' not found in /home/osmanlicom/store/app/code/iyzico/Iyzipay/Block/Adminhtml/Order/Creditmemo/Totals.php:17
Stack trace:
#0 /home/osmanlicom/store/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(136): require_once()
#1 /home/osmanlicom/store/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass('Iyzico\\Iyzipay\\...', '/home/osmanlico...')
#2 /home/osmanlicom/store/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(87): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract(Object(RecursiveIteratorIterator))
#3 /home/osmanlicom/store/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php(61): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList('/home/osmanlico...')
#4 /home/osmanlicom/store/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php(56): Magento\Setup\Module\Di\App\Task\Operation\RepositoryGe in /home/osmanlicom/store/app/code/iyzico/Iyzipay/Block/Adminhtml/Order/Creditmemo/Totals.php on line 17
```

**Comment by AlaaL** [comment]
Never mind it was case sensitive naming problem
